#ifndef UART_DRIVER_VERSION_H
#define UART_DRIVER_VERSION_H

#define UART_DRIVER_VERSION_MAJOR 1
#define UART_DRIVER_VERSION_MINOR 3
#define UART_DRIVER_VERSION_PATCH 0
#define UART_DRIVER_VERSION_STR   "1.3.0"

#endif /* UART_DRIVER_VERSION_H */
